#!/bin/bash

echo -e "Please enter your name: " 
read name
echo -e "please enter your city: " 
read city

echo "these are the details $name and $city saving.."
: '
output: 
Please enter your name:
Raj
please enter your city:
Banglore
these are the details Raj and Banglore saving..
'

echo -n "Please enter your firstname: " 
read fname
echo -n "please enter your lastname: " 
read lname

echo -e "\nThis is your fullname ${fname}${lname} saving.." 
: '
Please enter your firstname: raj
please enter your lastname: kumar

This is your fullname rajkumar saving..
'
===================================================================================================================================

we can reduce the size of code using  by directly defining a variable beside read command using -p option
The -p option in the read command in Bash is used to display a prompt message directly in the terminal before 
waiting for user input. This eliminates the need for using echo separately to display the prompt message.

read -p "please enter your name: " Name
read -p "please enter your idnumber: " Id

concatination="$Id $Name" 
echo -e "you ID and Name are saved: $concatination thank you:)"

: '
output: 
lease enter your name: raj
please enter your idnumber: 09
you ID and Name are saved: 09 raj thank you:)
'
#===================================================================================================================================

read -p "please enter your user_name: " Name
read -p "please enter your password: " pass

echo -e "you Deatils are saved.. thank you:)"

: '
please enter your user_name: ramesh
please enter your password: asajshb #----> we need to hide password for this we need to use -sp option 
you Deatils are saved.. thank you:)
'
read -p "please enter your user_name: " Name
read -sp "please enter your password: " pass

echo -e "\nyou Deatils are saved.. thank you:)"
: '
$ sh 06_readinput.sh
please enter your user_name: ramesh
please enter your password:         #--->userinput password is hidden..
you Deatils are saved.. thank you:)
'
====================================================================================================================================

#Error handling with readonly builtin commmand
: '
Scenario:: 
You are writing a shell script to define a configuration setting for a software application. 
You need to define a read-only variable for the application name and attempt to change it.
If the change is attempted, the script should show an error message.
'
readonly APP_Name="MyApplication1"
echo "Application Name: $APP_Name"
APP_Name="NewApp" 
echo "Updated Application Name: $APP_Name"

: '
output:
    Application Name: MyApplication1
    readonly2.sh: line 11: APP_Name: readonly variable
'

readonly APP_Name="MyApplication1"
echo "Application Name: $APP_Name"
# # Attempting to change a readonly variable 
APP_Name="NewApp" 2>/dev/null || echo "The variable APP_Name cannot be modified as it is readonly."

: '
2>/dev/null: Hides error messages by redirecting stderr to /dev/null.
|| echo "custom message": If the previous command fails, it displays a custom message.
The readonly error is hidden.
A user-friendly message is shown instead if the command fails.
2: Refers to stderr (standard error), which is the stream where error messages are sent.
>: This is the redirection operator, used to send output to a file or location.
/dev/null: A special location (null device) that discards any input sent to it. Its like a "black hole" for unwanted output.
Any error generated by command_that_fails will be discarded and not shown in the terminal.
This is useful when you want to suppress error messages or log them elsewhere.
'

#==================================================================================================================================