#!/bin/bash

# Define the logs folder path where logs will be saved
LOGS_FOLDER="/var/log/shell-script/" 
# This specifies that a folder named 'shell-script' will be created inside the '/var/log' directory.

# Create the directory if it does not already exist
mkdir -p $LOGS_FOLDER
# The `-p` option ensures that the directory structure is created, and no error is thrown if the folder already exists.

# Extract the name of the script (without the file extension)
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
# `$0` contains the name of the script being executed. 
# The `cut` command splits the string at the period (`.`) and selects the first part (script name).

# Generate a timestamp in the format `YYYY-MM-DD-HH-MM-SS`
TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)
# The `date` command is used to include the current date and time in the log file name.

# Define the log file name with the folder path, script name, and timestamp
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME-$TIMESTAMP.log"
# The log file will have a structured naming convention: 
#   `<script_name>-<timestamp>.log`
# Example: `02_output_logfile_redirctors-2025-01-09-06-02-12.log`

# Redirect outputs and errors to the log file
echo "Hello How are you?" &> $LOG_FILE
echo "I am fine thank you!.."
# The `&>` operator redirects both standard output and standard error to the log file.

ls -l /home/ec2-user/ &>> $LOG_FILE
# The `ls -l` command lists the contents of the `/home/ec2-user/` directory in long format.
# The `&>>` operator appends both standard output and standard error to the log file.

echo "Script started executing at: $(date)" &>> $LOG_FILE
# Logs the current timestamp when the script started executing, appending the message to the log file.

: '
Explanation:
1. The script creates a folder structure `/var/log/shell-script/`.
2. The log file is named with the format `<script_name>-<timestamp>.log`.
3. All outputs and errors generated by the script are redirected to the log file.
4. This log file provides a record of the scripts actions and their results.

Example:
After running the script:
Navigate to the folder: `cd /var/log/shell-script/`
List the contents: `ls -l`

Output Example:
-rw-r--r-- 1 root root 366 Jan  9 06:02 02_output_logfile_redirctors-2025-01-09-06-02-12.log

To view the log file contents:
cat 02_output_logfile_redirctors-2025-01-09-06-02-12.log

Log file contents:
Hello How are you?
total 8
-rw-r--r-- 1 ec2-user ec2-user 123 Jan  9 03:54 details.txt
drwxr-xr-x 2 ec2-user ec2-user   6 Jan  9 03:56 dev
-rw-r--r-- 1 ec2-user ec2-user 346 Jan  9 04:09 output.txt
drwxr-xr-x 3 ec2-user ec2-user  26 Jan  9 03:52 practice
drwxr-xr-x 2 ec2-user ec2-user   6 Jan  9 03:56 test
Script started executing at: Thu Jan  9 06:02:12 UTC 2025

Usage:
- Use this script for structured logging during automation or installations.
- The log file captures all outputs, providing a detailed execution history.
'